FROM python:3.10.15-slim

# Installation des dépendances système minimales
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    libffi-dev \
    libpq-dev \
    libssl-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Création d’un utilisateur sécurisé
RUN addgroup --system lafaom && adduser --system --ingroup lafaom lafaom

# Définition du dossier de travail
WORKDIR /app

# Copier le fichier requirements
COPY requirements.txt .

# Installation des dépendances Python
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copie des scripts d’entrée et de démarrage
COPY ./entrypoint /entrypoint
COPY ./start /start
RUN sed -i 's/\r$//g' /entrypoint /start && \
    chmod +x /entrypoint /start && \
    chown lafaom:lafaom /entrypoint /start

# Copie du code source
COPY . .

# Création des répertoires nécessaires avec les bonnes permissions
RUN mkdir -p /app/static/documents \
             /app/static/images \
             /app/static/audios \
             /app/static/videos \
             /app/logs && \
    chown -R lafaom:lafaom /app/static /app/logs

# Attribution finale des droits sur /app
RUN chown -R lafaom:lafaom /app

# Utilisation de l’utilisateur non-root
USER lafaom

# Exposition du port de l'application
EXPOSE 8000

# Point d’entrée
ENTRYPOINT ["/entrypoint"]
