"""Add objet field and update dossier constraints

Revision ID: 191985e5e4ea
Revises: 9ee38782e188
Create Date: 2025-08-31 08:07:18.654397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '191985e5e4ea'
down_revision: Union[str, Sequence[str], None] = '9ee38782e188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dossiers', sa.Column('objet', sa.Text(), nullable=True))
    op.alter_column('dossiers', 'date_soumission',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dossiers', 'date_soumission',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('dossiers', 'objet')
    # ### end Alembic commands ###
