"""users_change_of_change

Revision ID: 23ab5dca12c8
Revises: 8b3a1c4d6e7f
Create Date: 2025-08-10 20:32:46.857926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23ab5dca12c8'
down_revision: Union[str, Sequence[str], None] = '8b3a1c4d6e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_utilisateurs_formations',
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('formation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('utilisateur_id', 'formation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_utilisateurs_formations')
    # ### end Alembic commands ###
