"""add_type_paiement_to_paiements_cinetpay

Revision ID: 531952ebff87
Revises: 6a853fee8d2a
Create Date: 2025-09-02 17:01:19.637838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '531952ebff87'
down_revision: Union[str, Sequence[str], None] = '6a853fee8d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Ajouter la colonne avec une valeur par défaut
    op.add_column('paiements_cinetpay', sa.Column('type_paiement', sa.String(length=50), nullable=True))
    
    # Mettre à jour les valeurs existantes
    op.execute("UPDATE paiements_cinetpay SET type_paiement = 'FORMATION' WHERE type_paiement IS NULL")
    
    # Rendre la colonne NOT NULL
    op.alter_column('paiements_cinetpay', 'type_paiement', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paiements_cinetpay', 'type_paiement')
    # ### end Alembic commands ###
