"""add_cinetpay_payment_tables

Revision ID: 6a853fee8d2a
Revises: 8c16b32c4547
Create Date: 2025-09-02 16:22:58.469467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a853fee8d2a'
down_revision: Union[str, Sequence[str], None] = '8c16b32c4547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paiements_cinetpay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Integer(), nullable=False),
    sa.Column('devise', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('operator_id', sa.String(length=100), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('fund_availability_date', sa.DateTime(), nullable=True),
    sa.Column('metadata_paiement', sa.String(length=500), nullable=True),
    sa.Column('notify_url', sa.String(length=500), nullable=False),
    sa.Column('return_url', sa.String(length=500), nullable=False),
    sa.Column('payment_url', sa.String(length=500), nullable=True),
    sa.Column('payment_token', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paiements_cinetpay_id'), 'paiements_cinetpay', ['id'], unique=False)
    op.create_index(op.f('ix_paiements_cinetpay_transaction_id'), 'paiements_cinetpay', ['transaction_id'], unique=True)
    op.create_table('paiements_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('tentatives', sa.Integer(), nullable=True),
    sa.Column('prochaine_verification', sa.DateTime(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['paiements_cinetpay.transaction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paiements_queue_id'), 'paiements_queue', ['id'], unique=False)
    op.alter_column('reclamations', 'dossier_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reclamations', 'dossier_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_paiements_queue_id'), table_name='paiements_queue')
    op.drop_table('paiements_queue')
    op.drop_index(op.f('ix_paiements_cinetpay_transaction_id'), table_name='paiements_cinetpay')
    op.drop_index(op.f('ix_paiements_cinetpay_id'), table_name='paiements_cinetpay')
    op.drop_table('paiements_cinetpay')
    # ### end Alembic commands ###
