"""Initialisation

Revision ID: 828d8268d0a1
Revises: 
Create Date: 2025-08-05 17:36:16.620146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '828d8268d0a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('photo_couverture', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('specialite', sa.String(length=255), nullable=False),
    sa.Column('duree_mois', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'PLANIFIEE', 'EN_COURS', 'EN_PAUSE', 'TERMINEE', 'ANNULEE', 'ARCHIVEE', 'REJETEE', name='statutformationenum'), nullable=False),
    sa.Column('frais', sa.Float(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Formations avec spécialités et calendrier.'
    )
    op.create_index('idx_formation_dates', 'formations', ['date_debut', 'date_fin'], unique=False)
    op.create_index('idx_formation_status_dates', 'formations', ['statut', 'date_debut', 'date_fin'], unique=False)
    op.create_index(op.f('ix_formations_date_debut'), 'formations', ['date_debut'], unique=False)
    op.create_index(op.f('ix_formations_date_fin'), 'formations', ['date_fin'], unique=False)
    op.create_index(op.f('ix_formations_specialite'), 'formations', ['specialite'], unique=False)
    op.create_index(op.f('ix_formations_statut'), 'formations', ['statut'], unique=False)
    op.create_index(op.f('ix_formations_titre'), 'formations', ['titre'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.Enum('LIRE_FORMATION', 'MODIFIER_FORMATION', name='permissionenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom'),
    comment="Permissions pour contrôle d'accès."
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.Enum('ADMIN', 'COORDONNATEUR', 'FORMATEUR', 'REFERENT', 'APPRENANT', name='roleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom'),
    comment='Rôles des utilisateurs avec permissions associées.'
    )
    op.create_table('association_roles_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    comment='Associe rôles et permissions pour la gestion des droits.'
    )
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('photo_couverture', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('formation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Unités pédagogiques d’une formation.'
    )
    op.create_index(op.f('ix_modules_titre'), 'modules', ['titre'], unique=False)
    op.create_table('projets_collectifs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('piece_jointe', sa.String(length=255), nullable=True),
    sa.Column('formation_id', sa.Integer(), nullable=True),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'PLANIFIEE', 'EN_COURS', 'EN_PAUSE', 'TERMINEE', 'ANNULEE', 'ARCHIVEE', name='statutprojetcollectifenum'), nullable=False),
    sa.Column('date_debut', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Projets collaboratifs des apprenants.'
    )
    op.create_index('idx_projet_collectif_formation_statut', 'projets_collectifs', ['formation_id', 'statut'], unique=False)
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('prenom', sa.String(length=255), nullable=True),
    sa.Column('sexe', sa.Enum('HOMME', 'FEMME', 'AUTRE', name='sexeenum'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('statut', sa.Enum('ACTIF', 'INACTIF', 'SUPPRIMER', name='statutcompteenum'), nullable=False),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.Column('last_password_change', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('reset_token', sa.String(length=36), nullable=True),
    sa.Column('reset_token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Informations des utilisateurs (apprenants, formateurs, admins).'
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_table('accreditations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('formation_id', sa.Integer(), nullable=True),
    sa.Column('etablissement', sa.String(length=255), nullable=False),
    sa.Column('date_emission', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_expiration', sa.DateTime(timezone=True), nullable=True),
    sa.Column('statut', sa.Enum('PLANIFIEE', 'EN_COURS', 'TERMINEE', name='statutenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Accréditations pour accès aux établissements pénitentiaires.'
    )
    op.create_index('idx_accreditation_user_formation', 'accreditations', ['utilisateur_id', 'formation_id'], unique=False)
    op.create_table('actualites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('categorie', sa.String(length=100), nullable=False),
    sa.Column('chapeau', sa.Text(), nullable=False),
    sa.Column('contenu_html', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('date_publication', sa.Date(), nullable=False),
    sa.Column('date_debut_formation', sa.Date(), nullable=True),
    sa.Column('date_fin_formation', sa.Date(), nullable=True),
    sa.Column('document_url', sa.String(length=255), nullable=True),
    sa.Column('auteur', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    comment='Actualités et articles de blog.'
    )
    op.create_index(op.f('ix_actualites_id'), 'actualites', ['id'], unique=False)
    op.create_table('association_projets_collectifs_membres',
    sa.Column('projet_collectif_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projet_collectif_id'], ['projets_collectifs.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('projet_collectif_id', 'utilisateur_id'),
    comment='Associe membres aux projets collectifs.'
    )
    op.create_table('association_utilisateurs_permissions',
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('utilisateur_id', 'permission_id'),
    comment='Associe permissions directes aux utilisateurs.'
    )
    op.create_table('chefs_d_oeuvre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('piece_jointe', sa.String(length=255), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('statut', sa.Enum('EN_COURS', 'TERMINE', 'ABANDON', 'EN_CORRECTION', name='statutprojetindividuelenum'), nullable=False),
    sa.Column('date_soumission', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Float(), nullable=True),
    sa.Column('commentaires', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Projets individuels des apprenants (pédagogie Mao).'
    )
    op.create_index('idx_chef_oeuvre_user_module', 'chefs_d_oeuvre', ['utilisateur_id', 'module_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('QCM', 'OUVERTE', 'PRATIQUE', name='evaluationtypeenum'), nullable=False),
    sa.Column('consigne', sa.Text(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Évaluations pour tester les compétences.'
    )
    op.create_table('genotypes_individuels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DETENU', 'PROCHE', name='genotypetypeenum'), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('prenom', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sexe', sa.Enum('HOMME', 'FEMME', 'AUTRE', name='sexeenum'), nullable=True),
    sa.Column('motif_detention', sa.Text(), nullable=True),
    sa.Column('date_debut_detention', sa.Date(), nullable=True),
    sa.Column('duree_detention', sa.String(length=50), nullable=True),
    sa.Column('pays_detention', sa.String(length=255), nullable=True),
    sa.Column('maison_detention', sa.String(length=255), nullable=True),
    sa.Column('profession', sa.String(length=255), nullable=True),
    sa.Column('activite_avant_detention', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Données des détenus ou proches pour le génotype individuel.'
    )
    op.create_index('idx_genotype_detention', 'genotypes_individuels', ['type', 'maison_detention', 'date_debut_detention'], unique=False)
    op.create_index('idx_genotype_nom_prenom', 'genotypes_individuels', ['nom', 'prenom'], unique=False)
    op.create_index(op.f('ix_genotypes_individuels_date_debut_detention'), 'genotypes_individuels', ['date_debut_detention'], unique=False)
    op.create_index(op.f('ix_genotypes_individuels_maison_detention'), 'genotypes_individuels', ['maison_detention'], unique=False)
    op.create_index(op.f('ix_genotypes_individuels_nom'), 'genotypes_individuels', ['nom'], unique=False)
    op.create_index(op.f('ix_genotypes_individuels_pays_detention'), 'genotypes_individuels', ['pays_detention'], unique=False)
    op.create_index(op.f('ix_genotypes_individuels_prenom'), 'genotypes_individuels', ['prenom'], unique=False)
    op.create_index(op.f('ix_genotypes_individuels_type'), 'genotypes_individuels', ['type'], unique=False)
    op.create_index(op.f('ix_genotypes_individuels_utilisateur_id'), 'genotypes_individuels', ['utilisateur_id'], unique=False)
    op.create_table('inscriptions_formations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('formation_id', sa.Integer(), nullable=True),
    sa.Column('statut', sa.Enum('EN_COURS', 'TERMINER', name='statutinscriptionenum'), nullable=False),
    sa.Column('progression', sa.Float(), nullable=True),
    sa.Column('date_inscription', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_dernier_acces', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note_finale', sa.Float(), nullable=True),
    sa.Column('heures_formation', sa.Float(), nullable=True),
    sa.Column('montant_verse', sa.Float(), nullable=False, comment='Montant total versé pour la formation'),
    sa.Column('statut_paiement', sa.Enum('VERSEMENT_PARTIEL', 'AUCUN_VERSEMENT', 'TERMINE', name='statutpaiementenum'), nullable=False, comment='Statut du paiement'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Suivi des inscriptions, progression et paiements des apprenants.'
    )
    op.create_index('idx_inscription_user_formation', 'inscriptions_formations', ['utilisateur_id', 'formation_id'], unique=False)
    op.create_table('ressources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('DOCUMENT', 'IMAGE', 'AUDIO', 'VIDEO', name='filetypeenum'), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=True),
    sa.Column('lien', sa.String(length=255), nullable=True),
    sa.Column('description_du_lien', sa.Text(), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Ressources pédagogiques pour l’apprentissage.'
    )
    op.create_index(op.f('ix_ressources_titre'), 'ressources', ['titre'], unique=False)
    op.create_table('ascendance_genotypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genotype_id', sa.Integer(), nullable=True),
    sa.Column('nom_pere', sa.String(length=255), nullable=True),
    sa.Column('age_pere', sa.Integer(), nullable=True),
    sa.Column('tribu_pere', sa.String(length=255), nullable=True),
    sa.Column('ethnie_pere', sa.String(length=255), nullable=True),
    sa.Column('religion_pere', sa.String(length=255), nullable=True),
    sa.Column('situation_matrimoniale_pere', sa.String(length=255), nullable=True),
    sa.Column('profession_pere', sa.String(length=255), nullable=True),
    sa.Column('domicile_pere', sa.String(length=255), nullable=True),
    sa.Column('proprietaire_domicile_pere', sa.String(length=255), nullable=True),
    sa.Column('nom_mere', sa.String(length=255), nullable=True),
    sa.Column('age_mere', sa.Integer(), nullable=True),
    sa.Column('tribu_mere', sa.String(length=255), nullable=True),
    sa.Column('ethnie_mere', sa.String(length=255), nullable=True),
    sa.Column('religion_mere', sa.String(length=255), nullable=True),
    sa.Column('situation_matrimoniale_mere', sa.String(length=255), nullable=True),
    sa.Column('profession_mere', sa.String(length=255), nullable=True),
    sa.Column('domicile_mere', sa.String(length=255), nullable=True),
    sa.Column('proprietaire_domicile_mere', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['genotype_id'], ['genotypes_individuels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Informations d’ascendance pour le génotype.'
    )
    op.create_table('education_genotypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genotype_id', sa.Integer(), nullable=True),
    sa.Column('etablissements_frequentes', sa.Text(), nullable=True),
    sa.Column('derniere_classe', sa.String(length=255), nullable=True),
    sa.Column('date_arret_cours', sa.Date(), nullable=True),
    sa.Column('raisons_decrochage', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['genotype_id'], ['genotypes_individuels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('genotype_id'),
    comment='Informations éducatives pour le génotype.'
    )
    op.create_table('paiements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inscription_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False, comment='Montant du paiement'),
    sa.Column('date_paiement', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('methode_paiement', sa.Enum('CARTE_BANCAIRE', 'MOBILE_MONEY', 'VIREMENT_BANCAIRE', 'ESPECES', 'PESUPAY', name='methodepaiementenum'), nullable=False, comment='Méthode de paiement utilisée'),
    sa.Column('reference_transaction', sa.String(length=255), nullable=True, comment='Référence de la transaction (ex: ID PesuPay)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inscription_id'], ['inscriptions_formations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Historique des paiements pour chaque inscription.'
    )
    op.create_index('idx_paiement_inscription', 'paiements', ['inscription_id'], unique=False)
    op.create_table('plans_intervention_individualises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genotype_id', sa.Integer(), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('objectifs', sa.Text(), nullable=True),
    sa.Column('statut', sa.Enum('PLANIFIEE', 'EN_COURS', 'TERMINEE', name='statutenum'), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_mise_a_jour', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['genotype_id'], ['genotypes_individuels.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Plans d’intervention individualisés basés sur le génotype.'
    )
    op.create_index('idx_plan_dates', 'plans_intervention_individualises', ['date_creation', 'date_mise_a_jour'], unique=False)
    op.create_index('idx_plan_genotype_statut', 'plans_intervention_individualises', ['genotype_id', 'statut'], unique=False)
    op.create_index(op.f('ix_plans_intervention_individualises_genotype_id'), 'plans_intervention_individualises', ['genotype_id'], unique=False)
    op.create_index(op.f('ix_plans_intervention_individualises_utilisateur_id'), 'plans_intervention_individualises', ['utilisateur_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('QCM', 'OUVERTE', 'PRATIQUE', name='evaluationtypeenum'), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('piece_jointe', sa.String(length=255), nullable=True),
    sa.Column('evaluation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Questions des évaluations.'
    )
    op.create_index('idx_question_type_eval', 'questions', ['type', 'evaluation_id'], unique=False)
    op.create_index(op.f('ix_questions_evaluation_id'), 'questions', ['evaluation_id'], unique=False)
    op.create_table('resultats_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('evaluation_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Float(), nullable=True),
    sa.Column('date_soumission', sa.DateTime(timezone=True), nullable=True),
    sa.Column('commentaires', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Performances des apprenants aux évaluations.'
    )
    op.create_index('idx_resultat_date_note', 'resultats_evaluations', ['date_soumission', 'note'], unique=False)
    op.create_index('idx_resultat_user_eval', 'resultats_evaluations', ['utilisateur_id', 'evaluation_id'], unique=False)
    op.create_index(op.f('ix_resultats_evaluations_evaluation_id'), 'resultats_evaluations', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_resultats_evaluations_utilisateur_id'), 'resultats_evaluations', ['utilisateur_id'], unique=False)
    op.create_table('sante_genotypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genotype_id', sa.Integer(), nullable=True),
    sa.Column('maladie_chronique', sa.Text(), nullable=True),
    sa.Column('maladie_frequente', sa.Text(), nullable=True),
    sa.Column('maladie_haut_risque', sa.Text(), nullable=True),
    sa.Column('situation_vaccinale', sa.Text(), nullable=True),
    sa.Column('antecedents_medicaux', sa.Text(), nullable=True),
    sa.Column('maladie_hereditaire', sa.Text(), nullable=True),
    sa.Column('handicap', sa.Text(), nullable=True),
    sa.Column('allergie', sa.Text(), nullable=True),
    sa.Column('groupe_sanguin', sa.String(length=10), nullable=True),
    sa.Column('rhesus', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['genotype_id'], ['genotypes_individuels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('genotype_id'),
    comment='Informations sanitaires pour le génotype.'
    )
    op.create_table('propositions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texte', sa.Text(), nullable=False),
    sa.Column('est_correcte', sa.Boolean(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Options de réponse pour QCM.'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('propositions')
    op.drop_table('sante_genotypes')
    op.drop_index(op.f('ix_resultats_evaluations_utilisateur_id'), table_name='resultats_evaluations')
    op.drop_index(op.f('ix_resultats_evaluations_evaluation_id'), table_name='resultats_evaluations')
    op.drop_index('idx_resultat_user_eval', table_name='resultats_evaluations')
    op.drop_index('idx_resultat_date_note', table_name='resultats_evaluations')
    op.drop_table('resultats_evaluations')
    op.drop_index(op.f('ix_questions_evaluation_id'), table_name='questions')
    op.drop_index('idx_question_type_eval', table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_plans_intervention_individualises_utilisateur_id'), table_name='plans_intervention_individualises')
    op.drop_index(op.f('ix_plans_intervention_individualises_genotype_id'), table_name='plans_intervention_individualises')
    op.drop_index('idx_plan_genotype_statut', table_name='plans_intervention_individualises')
    op.drop_index('idx_plan_dates', table_name='plans_intervention_individualises')
    op.drop_table('plans_intervention_individualises')
    op.drop_index('idx_paiement_inscription', table_name='paiements')
    op.drop_table('paiements')
    op.drop_table('education_genotypes')
    op.drop_table('ascendance_genotypes')
    op.drop_index(op.f('ix_ressources_titre'), table_name='ressources')
    op.drop_table('ressources')
    op.drop_index('idx_inscription_user_formation', table_name='inscriptions_formations')
    op.drop_table('inscriptions_formations')
    op.drop_index(op.f('ix_genotypes_individuels_utilisateur_id'), table_name='genotypes_individuels')
    op.drop_index(op.f('ix_genotypes_individuels_type'), table_name='genotypes_individuels')
    op.drop_index(op.f('ix_genotypes_individuels_prenom'), table_name='genotypes_individuels')
    op.drop_index(op.f('ix_genotypes_individuels_pays_detention'), table_name='genotypes_individuels')
    op.drop_index(op.f('ix_genotypes_individuels_nom'), table_name='genotypes_individuels')
    op.drop_index(op.f('ix_genotypes_individuels_maison_detention'), table_name='genotypes_individuels')
    op.drop_index(op.f('ix_genotypes_individuels_date_debut_detention'), table_name='genotypes_individuels')
    op.drop_index('idx_genotype_nom_prenom', table_name='genotypes_individuels')
    op.drop_index('idx_genotype_detention', table_name='genotypes_individuels')
    op.drop_table('genotypes_individuels')
    op.drop_table('evaluations')
    op.drop_index('idx_chef_oeuvre_user_module', table_name='chefs_d_oeuvre')
    op.drop_table('chefs_d_oeuvre')
    op.drop_table('association_utilisateurs_permissions')
    op.drop_table('association_projets_collectifs_membres')
    op.drop_index(op.f('ix_actualites_id'), table_name='actualites')
    op.drop_table('actualites')
    op.drop_index('idx_accreditation_user_formation', table_name='accreditations')
    op.drop_table('accreditations')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_index('idx_projet_collectif_formation_statut', table_name='projets_collectifs')
    op.drop_table('projets_collectifs')
    op.drop_index(op.f('ix_modules_titre'), table_name='modules')
    op.drop_table('modules')
    op.drop_table('association_roles_permissions')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_formations_titre'), table_name='formations')
    op.drop_index(op.f('ix_formations_statut'), table_name='formations')
    op.drop_index(op.f('ix_formations_specialite'), table_name='formations')
    op.drop_index(op.f('ix_formations_date_fin'), table_name='formations')
    op.drop_index(op.f('ix_formations_date_debut'), table_name='formations')
    op.drop_index('idx_formation_status_dates', table_name='formations')
    op.drop_index('idx_formation_dates', table_name='formations')
    op.drop_table('formations')
    # ### end Alembic commands ###
