"""Fix formation_id nullable constraint

Revision ID: 9ee38782e188
Revises: 1b151e52b30d
Create Date: 2025-08-31 07:53:30.249076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee38782e188'
down_revision: Union[str, Sequence[str], None] = '1b151e52b30d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dossiers', 'formation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dossiers', 'formation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
