"""init

Revision ID: d91c37b8f14d
Revises: 
Create Date: 2025-08-24 15:09:24.556077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd91c37b8f14d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('ville', sa.String(length=120), nullable=True),
    sa.Column('code_postal', sa.String(length=50), nullable=True),
    sa.Column('pays', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_centres_nom'), 'centres', ['nom'], unique=True)
    op.create_table('formations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialite', sa.Enum('ACCUEIL', 'PENITENTIAIRE', 'ASSISTANCE', name='specialiteenum'), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('fiche_info', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duree_heures', sa.Integer(), nullable=True),
    sa.Column('type_formation', sa.Enum('COURTE', 'LONGUE', name='typeformationenum'), nullable=True),
    sa.Column('modalite', sa.Enum('PRESENTIEL', 'EN_LIGNE', name='modaliteenum'), nullable=False),
    sa.Column('pre_requis', sa.Text(), nullable=True),
    sa.Column('frais_inscription', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('frais_formation', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('devise', sa.Enum('EUR', 'XAF', 'XOF', 'USD', name='deviseenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_formation_type_modalite', 'formations', ['type_formation', 'modalite'], unique=False)
    op.create_index(op.f('ix_formations_fiche_info'), 'formations', ['fiche_info'], unique=False)
    op.create_index(op.f('ix_formations_specialite'), 'formations', ['specialite'], unique=False)
    op.create_index(op.f('ix_formations_titre'), 'formations', ['titre'], unique=False)
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('civilite', sa.Enum('MONSIEUR', 'MADAME', 'MADEMOISELLE', 'AUTRE', name='civiliteenum'), nullable=True),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telephone_mobile', sa.String(length=30), nullable=True),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('nationalite', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CANDIDAT', 'ADMIN', name='roleenum'), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('situation_professionnelle', sa.String(length=120), nullable=True),
    sa.Column('experience_professionnelle_en_mois', sa.Integer(), nullable=True),
    sa.Column('employeur', sa.String(length=120), nullable=True),
    sa.Column('categorie_socio_professionnelle', sa.String(length=120), nullable=True),
    sa.Column('fonction', sa.String(length=120), nullable=True),
    sa.Column('dernier_diplome_obtenu', sa.String(length=120), nullable=True),
    sa.Column('date_obtention_dernier_diplome', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_index(op.f('ix_utilisateurs_nom'), 'utilisateurs', ['nom'], unique=False)
    op.create_index(op.f('ix_utilisateurs_prenom'), 'utilisateurs', ['prenom'], unique=False)
    op.create_index(op.f('ix_utilisateurs_telephone_mobile'), 'utilisateurs', ['telephone_mobile'], unique=False)
    op.create_table('adresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('type_adresse', sa.String(length=50), nullable=False),
    sa.Column('pays', sa.String(length=100), nullable=True),
    sa.Column('ville', sa.String(length=120), nullable=True),
    sa.Column('rue', sa.String(length=255), nullable=True),
    sa.Column('code_postal', sa.String(length=50), nullable=True),
    sa.Column('province', sa.String(length=120), nullable=True),
    sa.Column('pays_facturation', sa.String(length=100), nullable=True),
    sa.Column('ville_facturation', sa.String(length=120), nullable=True),
    sa.Column('rue_facturation', sa.String(length=255), nullable=True),
    sa.Column('code_postal_facturation', sa.String(length=50), nullable=True),
    sa.Column('province_facturation', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilisateur_id', 'type_adresse', name='uq_adresse_user_type')
    )
    op.create_index('ix_adresse_user', 'adresses', ['utilisateur_id'], unique=False)
    op.create_table('informations_descriptives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formation_id', sa.Integer(), nullable=False),
    sa.Column('presentation', sa.Text(), nullable=True, comment="Contexte, enjeux et vision d'ensemble de la formation"),
    sa.Column('avantages', sa.Text(), nullable=True, comment='Avantages et spécificités de la formation'),
    sa.Column('points_forts', sa.Text(), nullable=True, comment='Points forts de la formation (liste)'),
    sa.Column('competences_visees', sa.Text(), nullable=True, comment='Compétences et savoir-faire à acquérir'),
    sa.Column('programme', sa.Text(), nullable=True, comment='Contenu détaillé et structure de la formation'),
    sa.Column('profils_cibles', sa.Text(), nullable=True, comment='Public cible et prérequis'),
    sa.Column('inscription', sa.Text(), nullable=True, comment="Modalités d'inscription, durée, rythme"),
    sa.Column('certifications', sa.Text(), nullable=True, comment='Certifications et attestations disponibles'),
    sa.Column('methode_pedagogique', sa.Text(), nullable=True, comment='Approche pédagogique et outils utilisés'),
    sa.Column('evaluation', sa.Text(), nullable=True, comment="Modalités d'évaluation et validation"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('formation_id')
    )
    op.create_index(op.f('ix_informations_descriptives_id'), 'informations_descriptives', ['id'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formation_id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('formation_id', 'titre', name='uq_module_formation_titre')
    )
    op.create_index(op.f('ix_modules_ordre'), 'modules', ['ordre'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formation_id', sa.Integer(), nullable=False),
    sa.Column('centre_id', sa.Integer(), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('date_limite_inscription', sa.Date(), nullable=True),
    sa.Column('places_disponibles', sa.Integer(), nullable=True),
    sa.Column('statut', sa.Enum('OUVERTE', 'FERMEE', 'ANNULEE', name='statutsessionenum'), nullable=False),
    sa.Column('modalite', sa.Enum('PRESENTIEL', 'EN_LIGNE', name='modaliteenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_dates', 'sessions', ['date_debut', 'date_fin'], unique=False)
    op.create_index('ix_session_formation', 'sessions', ['formation_id'], unique=False)
    op.create_table('dossiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('formation_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('numero_candidature', sa.String(length=50), nullable=True),
    sa.Column('statut', sa.Enum('RECUE', 'EN_ETUDE', 'ACCEPTÉE', 'REFUSÉE', 'ANNULEE', name='statutcandidatureenum'), nullable=False),
    sa.Column('date_soumission', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motif_refus', sa.Text(), nullable=True),
    sa.Column('frais_inscription_montant', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('frais_formation_montant', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('devise', sa.Enum('EUR', 'XAF', 'XOF', 'USD', name='deviseenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilisateur_id', 'session_id', name='uq_dossier_user_session')
    )
    op.create_index('ix_dossier_statut', 'dossiers', ['statut'], unique=False)
    op.create_index('ix_dossier_user', 'dossiers', ['utilisateur_id'], unique=False)
    op.create_index(op.f('ix_dossiers_numero_candidature'), 'dossiers', ['numero_candidature'], unique=True)
    op.create_table('ressources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('type_ressource', sa.Enum('PDF', 'VIDEO', 'AUDIO', 'LIEN', 'AUTRE', name='typeressourceenum'), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ressource_type', 'ressources', ['type_ressource'], unique=False)
    op.create_table('paiements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('type_paiement', sa.Enum('INSCRIPTION', 'FORMATION', name='typepaiementenum'), nullable=False),
    sa.Column('montant', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('devise', sa.Enum('EUR', 'XAF', 'XOF', 'USD', name='deviseenum'), nullable=False),
    sa.Column('statut', sa.Enum('PENDING', 'ACCEPTED', 'REFUSED', 'CANCELLED', 'ERROR', 'REPAY', name='statutpaiementenum'), nullable=False),
    sa.Column('methode', sa.Enum('MOBILE_MONEY', 'ALL', 'CARTE', 'VIREMENT', 'ESPECES', name='methodepaiementenum'), nullable=True),
    sa.Column('reference_externe', sa.String(length=120), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('paye_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_echeance', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paiement_type_statut', 'paiements', ['type_paiement', 'statut'], unique=False)
    op.create_index(op.f('ix_paiements_reference_externe'), 'paiements', ['reference_externe'], unique=False)
    op.create_table('pieces_jointes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('type_document', sa.String(length=100), nullable=False),
    sa.Column('chemin_fichier', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_upload', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_piece_type', 'pieces_jointes', ['type_document'], unique=False)
    op.create_table('reclamations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('auteur_id', sa.Integer(), nullable=False),
    sa.Column('numero_reclamation', sa.String(length=50), nullable=True),
    sa.Column('objet', sa.String(length=255), nullable=False),
    sa.Column('type_reclamation', sa.String(length=100), nullable=True),
    sa.Column('priorite', sa.String(length=50), nullable=True),
    sa.Column('statut', sa.Enum('NOUVEAU', 'EN_COURS', 'CLOTURE', name='statutreclamationenum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_cloture', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auteur_id'], ['utilisateurs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reclamation_statut', 'reclamations', ['statut'], unique=False)
    op.create_index(op.f('ix_reclamations_numero_reclamation'), 'reclamations', ['numero_reclamation'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reclamations_numero_reclamation'), table_name='reclamations')
    op.drop_index('ix_reclamation_statut', table_name='reclamations')
    op.drop_table('reclamations')
    op.drop_index('ix_piece_type', table_name='pieces_jointes')
    op.drop_table('pieces_jointes')
    op.drop_index(op.f('ix_paiements_reference_externe'), table_name='paiements')
    op.drop_index('ix_paiement_type_statut', table_name='paiements')
    op.drop_table('paiements')
    op.drop_index('ix_ressource_type', table_name='ressources')
    op.drop_table('ressources')
    op.drop_index(op.f('ix_dossiers_numero_candidature'), table_name='dossiers')
    op.drop_index('ix_dossier_user', table_name='dossiers')
    op.drop_index('ix_dossier_statut', table_name='dossiers')
    op.drop_table('dossiers')
    op.drop_index('ix_session_formation', table_name='sessions')
    op.drop_index('ix_session_dates', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_modules_ordre'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_informations_descriptives_id'), table_name='informations_descriptives')
    op.drop_table('informations_descriptives')
    op.drop_index('ix_adresse_user', table_name='adresses')
    op.drop_table('adresses')
    op.drop_index(op.f('ix_utilisateurs_telephone_mobile'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_prenom'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_nom'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_index(op.f('ix_formations_titre'), table_name='formations')
    op.drop_index(op.f('ix_formations_specialite'), table_name='formations')
    op.drop_index(op.f('ix_formations_fiche_info'), table_name='formations')
    op.drop_index('ix_formation_type_modalite', table_name='formations')
    op.drop_table('formations')
    op.drop_index(op.f('ix_centres_nom'), table_name='centres')
    op.drop_table('centres')
    # ### end Alembic commands ###
